id: IFD228646
ocr_import_info:
  timestamp: '2023-07-07T06:16:50.669385+00:00'
  batch_id: batch-ecde
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: PechaJobs
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-07-09 22:04:21.509755+00:00
last_modified: 2023-07-09 22:04:21.509764+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1NLM2140
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1NLM2140
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དབུ་མ་ལ་འཇུག་པ་སོགས།
  languages:
  - bo
  author: ཟླ་བ་གྲགས་པ།
statistics:
  ocr_word_mean_confidence_index: 0.9474409808057641
  ocr_word_median_confidence_index: 0.99462354
bases:
  I1NLM2140_001:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1NLM2140_001
      total_pages: 314
      volume_number: 1
      volume_pages_bdrc_intro: 0
    order: 1
    base_file: I1NLM2140_001.txt
    statistics:
      ocr_word_median_confidence_index: 0.99462354
      ocr_word_mean_confidence_index: 0.9474409808057641
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
